name: JavaFX Native Release

on:
  push:
    branches:
      - "main"
    tags:
      - v*.*.*

permissions:
  contents: write  # Required for release creation

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Download JavaFX SDK
        shell: bash
        run: |
          PLATFORM=$([[ "${{ matrix.os }}" == "windows-latest" ]] && echo "windows-x64" || ([[ "${{ matrix.os }}" == "macos-latest" ]] && echo "osx-x64" || echo "linux-x64"))
          curl -L -o javafx-sdk.zip https://download2.gluonhq.com/openjfx/21.0.1/openjfx-21.0.1_${PLATFORM}_bin-sdk.zip
          unzip javafx-sdk.zip
          mv javafx-sdk-21.0.1 javafx-sdk

      - name: Prepare App Directory
        run: |
          mkdir -p target/app
          mkdir -p target/jpackage
          cp employee-tracking-system-1.0-SNAPSHOT-shaded.jar target/app/main.jar
        # Uncomment if you have dependencies:
        # cp dependencies/*.jar target/app/ || true

      # Create Custom Runtime (Windows)
      - name: Create Custom Runtime (Windows)
        if: matrix.os == 'windows-latest'
        shell: cmd
        run: |
          if exist custom-runtime rmdir /s /q custom-runtime
          jlink ^
            --module-path "%JAVA_HOME%\jmods;target\app;javafx-sdk\lib" ^
            --add-modules java.base,java.logging,java.net.http,javafx.controls,javafx.fxml,javafx.media,jdk.unsupported,jdk.crypto.ec ^
            --output custom-runtime ^
            --strip-debug ^
            --compress 2 ^
            --no-header-files ^
            --no-man-pages

      # Create Custom Runtime (macOS/Linux)
      - name: Create Custom Runtime (macOS/Linux)
        if: matrix.os != 'windows-latest'
        shell: bash
        run: |
          rm -rf custom-runtime
          jlink \
            --module-path "$JAVA_HOME/jmods:target/app:javafx-sdk/lib" \
            --add-modules java.base,java.logging,java.net.http,javafx.controls,javafx.fxml,javafx.media,jdk.unsupported,jdk.crypto.ec \
            --output custom-runtime \
            --strip-debug \
            --compress 2 \
            --no-header-files \
            --no-man-pages

      # Test launching app with custom runtime (important debug step)
      - name: Test custom runtime launch
        shell: bash
        run: |
          echo "Testing custom runtime launch..."
          ./custom-runtime/bin/java -cp target/app/main.jar com.itrtechsystems.employeetrackingsystem.Main || (echo "Custom runtime launch FAILED!" && exit 1)

      # Create Windows Installer (MSI)
      - name: Create Windows Installer (MSI)
        if: matrix.os == 'windows-latest'
        shell: cmd
        run: |
          jpackage ^
            --verbose ^
            --type msi ^
            --input target\app ^
            --dest target\jpackage ^
            --name Trackivo ^
            --main-jar main.jar ^
            --main-class com.itrtechsystems.employeetrackingsystem.Main ^
            --icon resources\com\itrtechsystems\employeetrackingsystem\images\icon\icon.ico ^
            --app-version 1.1 ^
            --vendor "ITR Consulting" ^
            --win-menu ^
            --win-shortcut ^
            --install-dir Trackivo ^
            --runtime-image custom-runtime ^
            --java-options "-Dfile.encoding=UTF-8" ^
            --license-file resources\com\itrtechsystems\employeetrackingsystem\text\LICENSE.txt

      # Create macOS Installer (DMG)
      - name: Create macOS Installer (DMG)
        if: matrix.os == 'macos-latest'
        shell: bash
        run: |
          jpackage \
            --verbose \
            --type dmg \
            --input target/app \
            --dest target/jpackage \
            --name Trackivo \
            --main-jar main.jar \
            --main-class com.itrtechsystems.employeetrackingsystem.Main \
            --icon resources/com/itrtechsystems/employeetrackingsystem/images/icon/mac-icon.icns \
            --app-version 1.1 \
            --vendor "ITR Consulting" \
            --runtime-image custom-runtime \
            --java-options "-Dfile.encoding=UTF-8"

      # Create Linux Installer (DEB)
      - name: Create Linux Installer (DEB)
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y fakeroot
          jpackage \
            --verbose \
            --type deb \
            --input target/app \
            --dest target/jpackage \
            --name Trackivo \
            --main-jar main.jar \
            --main-class com.itrtechsystems.employeetrackingsystem.Main \
            --icon resources/com/itrtechsystems/employeetrackingsystem/images/icon/favicon-itr-logo.png \
            --app-version 1.1 \
            --vendor "ITR Consulting" \
            --runtime-image custom-runtime \
            --java-options "-Dfile.encoding=UTF-8"

      - name: Upload OS-specific artifact
        uses: actions/upload-artifact@v4
        with:
          name: installers-${{ matrix.os }}
          path: target/jpackage/*

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-files

      - name: List downloaded installers
        run: ls -R release-files

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: release-files/**/*
